services:
  lambda:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh:ro
    user: "${UID}:${GID}"

    tty: true
    working_dir: /workspace
    env_file:
      - .env
    shm_size: 256gb
